spring:
  config:
    activate:
      on-profile: prd
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # https://www.devglan.com/online-tools/jasypt-online-encryption-decryption
    # Password: System.getenv("JASYPT_PASSWD")
    url: ENC(P1mUsyLqf3knuUcUmdwqfIvePtNRVbfQ1+mWrKDP4llgjOX/a4/lyDwB8OAtK9QP)
    username: ENC(hWgPVHRFzZT9ox2650Gbsg==)
    password: ENC(nakhqJb9GyYZpIgFUW37/Q==)
    hikari:
      maximum-pool-size: 3
      connection-timeout: 5000
      connection-init-sql: SELECT 1
      validation-timeout: 2000
      minimum-idle: 10
      idle-timeout: 600000
      max-lifetime: 1800000
jwt:
  secret: PbiQO0ltYWXbbUe48qo3L4DR1u2KeC4+DOQfiKyOEOU=
  token-expires-in-seconds: 180
