server:
  port: 8080
  compression:
    enabled: true

spring:
  profiles:
    default: dev
  application:
    name: quartzManager
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/databasename
    username: user
    password: password
    hikari:
      maximum-pool-size: 3
      connection-timeout: 5000
      connection-init-sql: SELECT 1
      validation-timeout: 2000
      minimum-idle: 10
      idle-timeout: 600000
      max-lifetime: 1800000
  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: never
    properties:
      org:
        quartz:
          scheduler:
            instanceName: quartzapp01
            instanceId: AUTO
            classLoadHelper:
              class: com.home.quartzapp.scheduler.exception.ClassNotFoundIgnoringClassLoadHelper
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 5
          jobStore:
            class: org.quartz.impl.jdbcjobstore.JobStoreTX
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
            tablePrefix: QRTZ_
            isClustered: false
            clusterCheckinInterval: 20000
            dataSource: myDS
          dataSource:
            myDS:
              provider: hikaricp
              driver: com.mysql.cj.jdbc.Driver
              URL: jdbc:mysql://localhost:3306/databasename
              username: user
              password: password
              maxConnections: 5
              validationQuery: select 0 from dual
logging:
  level:
    com.home.quartzapp.scheduler.repository: DEBUG

mybatis:
  mapper-locations: classpath:**/*.xml
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 500
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

jwt:
  header: Authorization
  secret: PbiQO0ltYWXbbUe48qo3L4DR1u2KeC4+DOQfiKyOEOU=
  expiration-time-seconds: 180
