spring:
  config:
    activate:
      on-profile: local
  h2:
    console:
      enabled: true  # H2 Console 사용여부
      path: /h2-console  # H2 Console Path
  jpa:
    database: h2
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:/home/proj/quartz/quartzapp-h2;DATABASE_TO_UPPER=TRUE;AUTO_SERVER=TRUE
    username: sa
    password:

logging:
  level:
    jdbc:
      resultsettable: info
