server:
  port: 8080
  compression:
    enabled: true

spring:
  profiles:
    default: local
  application:
    name: quartzManager
  h2:
    console:
      enabled: false  # H2 Console 사용여부
  jpa:
    database: mysql
    show-sql: false
    ddl-auto: none
    properties:
      hibernate:
        format_sql: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/databasename
    username: user
    password: password
    hikari:
      maximum-pool-size: 3
      connection-timeout: 5000
      connection-init-sql: SELECT 1
      validation-timeout: 2000
      minimum-idle: 10
      idle-timeout: 600000
      max-lifetime: 1800000
  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: never
    properties:
      org:
        quartz:
          scheduler:
            instanceName: quartzapp01
            instanceId: AUTO
            rmi:
              export: false
              proxy: false
            classLoadHelper:
              class: com.home.quartzapp.scheduler.exception.ClassNotFoundIgnoringClassLoadHelper
            idleWaitTime: 10000
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 5
            threadPriority: 5
          jobStore:
            misfireThreshold: 10000
            isClustered: false
            clusterCheckinInterval: 60000
            lockHandler:
              class: org.quartz.impl.jdbcjobstore.UpdateLockRowSemaphore
            acquireTriggersWithinLock: true
          plugin:
            triggHistory:
              class: org.quartz.plugins.history.LoggingJobHistoryPlugin
  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: never

logging:
  level:
    root: info
    com.home.quartzapp: info
    org.hibernate.SQL: info
    org.hibernate.type.descriptor.sql: info
    org.hibernate.orm.jdbc.bind: info

mybatis:
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 500
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl

jwt:
  header: Authorization
  secret: PbiQO0ltYWXbbUe48qo3L4DR1u2KeC4+DOQfiKyOEOU=
  expiration-time-seconds: 3600
  refresh-expiration-time-seconds: 86400

springdoc:
  swagger-ui:
    enabled: true
