spring:
  config:
    activate:
      on-profile: prd
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # https://www.devglan.com/online-tools/jasypt-online-encryption-decryption
    # Password: JASYPT_ENCRYPTOR_PASSWORD environment variable value
    url: ENC(jvqHWEjN1+qqQA/Fah847ZA5ZLWtkgG377b0BKYOHhd4BCOCt0Sde9UCKYzVgn6V)
    username: ENC(sT7HF2JQTrQ+DC5H+UI9jQ==)
    password: ENC(r/+MDqanhGst8fLJOsNnHw==)
    hikari:
      maximum-pool-size: 3
      connection-timeout: 5000
      connection-init-sql: SELECT 1
      validation-timeout: 2000
      minimum-idle: 10
      idle-timeout: 600000
      max-lifetime: 1800000
jwt:
  secret: PbiQO0ltYWXbbUe48qo3L4DR1u2KeC4+DOQfiKyOEOU=
  expiration-time-seconds: 3600
  refresh-expiration-time-seconds: 86400

springdoc:
  swagger-ui:
    enabled: false