server:
  port: 8080
  compression:
    enabled: true

spring:
  profiles:
    default: dev
  application:
    name: quartzManager
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/databasename
    username: user
    password: password
    hikari:
      maximum-pool-size: 3
      connection-timeout: 5000
      connection-init-sql: SELECT 1
      validation-timeout: 2000
      minimum-idle: 10
      idle-timeout: 600000
      max-lifetime: 1800000
  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: never
    properties:
      org:
        quartz:
          scheduler:
            instanceName: quartzapp01
            instanceId: AUTO
            classLoadHelper:
              class: com.home.quartzapp.scheduler.exception.ClassNotFoundIgnoringClassLoadHelper
            idleWaitTime: 10000
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 5
logging:
  level:
    root: warn
    com.home.quartzapp: debug

mybatis:
  mapper-locations: classpath:**/*.xml
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 500
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl

jwt:
  header: Authorization
  secret: PbiQO0ltYWXbbUe48qo3L4DR1u2KeC4+DOQfiKyOEOU=
  expiration-time-seconds: 3600
  refresh-expiration-time-seconds: 86400
