create table QRTZ_JOB_HISTORY
(
    SCHED_NAME    CHARACTER VARYING(120) not null,
    ENTRY_ID      CHARACTER VARYING(95)  not null,
    TRIGGER_NAME  CHARACTER VARYING(190) not null,
    TRIGGER_GROUP CHARACTER VARYING(190) not null,
    JOB_NAME      CHARACTER VARYING(190),
    JOB_GROUP     CHARACTER VARYING(190),
    JOB_DATA      CHARACTER VARYING(4096),
    START_TIME    TIMESTAMP              not null,
    END_TIME      TIMESTAMP,
    STATUS        CHARACTER VARYING(16)  not null,
    EXIT_MESSAGE  CHARACTER VARYING(2500),
    primary key (SCHED_NAME, ENTRY_ID)
);

